defaultSemverRangePrefix: ''

nodeLinker: node-modules

packageExtensions:
  '@nrwl/cypress@*':
    peerDependencies:
      nx: '*'
      typescript: '*'
    peerDependenciesMeta:
      typescript:
        optional: true
  '@nrwl/eslint-plugin-nx@*':
    peerDependencies:
      nx: '*'
      eslint: '*'
      '@typescript-eslint/parser': '*'
    peerDependenciesMeta:
      typescript:
        optional: true
  '@nrwl/devkit@*':
    peerDependencies:
      nx: '*'
      typescript: '*'
    peerDependenciesMeta:
      typescript:
        optional: true
  '@nrwl/jest@*':
    peerDependencies:
      nx: '*'
  '@nrwl/js@*':
    peerDependencies:
      nx: '*'
      typescript: '*'
    peerDependenciesMeta:
      typescript:
        optional: true
  '@nrwl/linter@*':
    peerDependencies:
      nx: '*'
  '@nrwl/next@*':
    peerDependencies:
      '@babel/core': '*'
      eslint: '*'
      next: '*'
      nx: '*'
      tsconfig-paths-webpack-plugin: '*'
  '@nrwl/react@*':
    peerDependencies:
      '@types/node': '*'
      eslint: '*'
      nx: '*'
      webpack: '*'
  '@nrwl/rollup@*':
    peerDependencies:
      '@babel/core': '*'
      nx: '*'
      typescript: '*'
    peerDependenciesMeta:
      typescript:
        optional: true
  '@nrwl/storybook@*':
    peerDependencies:
      nx: '*'
      webpack: '*'
  '@nrwl/web@*':
    peerDependencies:
      nx: '*'
  '@nrwl/webpack@*':
    peerDependencies:
      '@types/node': '*'
      nx: '*'
  '@nx/cypress@*':
    peerDependencies:
      nx: '*'
      typescript: '*'
  '@nx/eslint-plugin@*':
    peerDependencies:
      eslint: '*'
      nx: '*'
  '@nx/jest@*':
    peerDependencies:
      nx: '*'
      typescript: '*'
    peerDependenciesMeta:
      typescript:
        optional: true
  '@nx/js@*':
    peerDependencies:
      nx: '*'
      typescript: '*'
    peerDependenciesMeta:
      typescript:
        optional: true
  '@nx/linter@*':
    peerDependencies:
      nx: '*'
      typescript: '*'
    peerDependenciesMeta:
      typescript:
        optional: true
  '@nx/next@*':
    peerDependencies:
      '@babel/core': '*'
      '@types/node': '*'
      dotenv: '*'
      eslint: '*'
      express: '*'
      nx: '*'
      tsconfig-paths-webpack-plugin: '*'
      typescript: '*'
      webpack: '*'
    peerDependenciesMeta:
      '@types/node':
        optional: true
      typescript:
        optional: true
      webpack:
        optional: true
  '@nx/react@*':
    peerDependencies:
      '@types/node': '*'
      eslint: '*'
      nx: '*'
      stylus: '*'
      typescript: '*'
      webpack: '*'
    peerDependenciesMeta:
      stylus:
        optional: true
      typescript:
        optional: true
  '@nx/rollup@*':
    peerDependencies:
      '@babel/core': '*'
      nx: '*'
      typescript: '*'
    peerDependenciesMeta:
      typescript:
        optional: true
  '@nx/storybook@*':
    peerDependencies:
      nx: '*'
      typescript: '*'
      webpack: '*'
    peerDependenciesMeta:
      typescript:
        optional: true
  '@nx/web@*':
    peerDependencies:
      '@types/node': '*'
      nx: '*'
      typescript: '*'
    peerDependenciesMeta:
      '@types/node':
        optional: true
      typescript:
        optional: true
  '@nx/webpack@*':
    peerDependencies:
      '@babel/core': '*'
      '@types/node': '*'
      nx: '*'
      typescript: '*'
    peerDependenciesMeta:
      typescript:
        optional: true
  '@storybook/addon-essentials@*':
    peerDependencies:
      '@babel/core': '*'
      webpack: '*'
  '@storybook/addon-docs@*':
    peerDependencies:
      '@babel/core': '*'
      webpack: '*'
  '@storybook/core-server@*':
    peerDependencies:
      react: '*'
      react-dom: '*'
  '@storybook/docs-tools@*':
    peerDependencies:
      react: '*'
      react-dom: '*'
  '@storybook/telemetry@*':
    peerDependencies:
      react: '*'
      react-dom: '*'
  stylelint-config-recommended-scss@*:
    peerDependenciesMeta:
      postcss:
        optional: true

yarnPath: .yarn/releases/yarn-3.2.3.cjs
