defaultSemverRangePrefix: ""

nodeLinker: node-modules

packageExtensions:
  "@nrwl/cypress@*":
    peerDependencies:
      nx: "*"
      typescript: "*"
  "@nrwl/eslint-plugin-nx@*":
    peerDependencies:
      eslint: "*"
      nx: "*"
  "@nrwl/jest@*":
    peerDependencies:
      nx: "*"
      typescript: "*"
    peerDependenciesMeta:
      typescript:
        optional: true
  "@nrwl/js@*":
    peerDependencies:
      nx: "*"
      typescript: "*"
    peerDependenciesMeta:
      typescript:
        optional: true
  "@nrwl/linter@*":
    peerDependencies:
      typescript: "*"
    peerDependenciesMeta:
      typescript:
        optional: true
  "@nrwl/next@*":
    peerDependencies:
      "@babel/core": "*"
      "@types/node": "*"
      dotenv: "*"
      eslint: "*"
      express: "*"
      nx: "*"
      tsconfig-paths-webpack-plugin: "*"
      typescript: "*"
      webpack: "*"
    peerDependenciesMeta:
      "@types/node":
        optional: true
      typescript:
        optional: true
      webpack:
        optional: true
  "@nrwl/react@*":
    peerDependencies:
      eslint: "*"
      nx: "*"
      typescript: "*"
    peerDependenciesMeta:
      typescript:
        optional: true
  "@nrwl/storybook@*":
    peerDependencies:
      nx: "*"
      typescript: "*"
      webpack: "*"
    peerDependenciesMeta:
      typescript:
        optional: true
  "@nrwl/web@*":
    peerDependencies:
      "@types/node": "*"
      nx: "*"
      typescript: "*"
    peerDependenciesMeta:
      "@types/node":
        optional: true
      typescript:
        optional: true
  "@storybook/addon-docs@*":
    peerDependencies:
      "@babel/core": "*"
      webpack: "*"
    peerDependenciesMeta:
      "@babel/core":
        optional: true
      webpack:
        optional: true
  "@storybook/docs-tools@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "@storybook/mdx1-csf@*":
    peerDependencies:
      "@babel/core": "*"
    peerDependenciesMeta:
      "@babel/core":
        optional: true
  "@storybook/telemetry@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "@yarn-tool/resolve-package@*":
    peerDependencies:
      "@types/node": "*"
    peerDependenciesMeta:
      "@types/node":
        optional: true
  storybook-dark-mode@*:
    peerDependenciesMeta:
      "@storybook/addons":
        optional: true
      "@storybook/api":
        optional: true
      "@storybook/components":
        optional: true
      "@storybook/core-events":
        optional: true
      "@storybook/theming":
        optional: true
  stylelint-config-recommended-scss@*:
    peerDependenciesMeta:
      postcss:
        optional: true

yarnPath: .yarn/releases/yarn-3.2.3.cjs
