[build]

  # Default build command.
  command = "yarn build"

  # Directory for build output
  publish = "build"

  # Directory with the serverless Lambda functions to deploy to AWS.
  # functions = "functions"

  # We can define other environment variables here as well... do not include secret tokens!
  environment = { NODE_VERSION = "14.5.0" }
