version: 2.1

orbs:
  node: circleci/node@3.0.1

jobs:
  test:
    executor:
      name: node/default
      tag: '12.16.3'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test --ci --runInBand --reporters=default --reporters=jest-junit
          name: Run tests
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./coverage/junit/
      - store_test_results:
          path: ./coverage/junit/
      - store_artifacts:
          path: ./coverage

workflows:
  test:
    jobs:
      - test
