version: 2.1

orbs:
  node: circleci/node@3.0.1

jobs:
  test:
    executor:
      name: node/default
      tag: '12.16.3'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run tests

workflows:
  test:
    jobs:
      - test
