version: 2.1

orbs:
  node: circleci/node@3.0.1

jobs:
  install:
    executor:
      name: node/default
      tag: 'lts'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - save_cache:
          key: bjeco-INSTALLED-{{ .Revision }}
          paths:
            - ~/

  test:
    executor:
      name: node/default
      tag: 'lts'
    steps:
      - restore_cache:
          key: bjeco-INSTALLED-{{ .Revision }}
      - run:
          command: yarn test --ci --runInBand --reporters=default --reporters=jest-junit
          name: Run Jest
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./coverage/junit/
      - store_test_results:
          path: ./coverage/junit/
      - store_artifacts:
          path: ./coverage

  lint:
    executor:
      name: node/default
      tag: 'lts'
    steps:
      - restore_cache:
          key: bjeco-INSTALLED-{{ .Revision }}
      - run:
          name: Run Eslint
          command: yarn lint --format junit --output-file ./coverage/eslint.xml
      - store_test_results:
          path: ./coverage
      - store_artifacts:
          path: ./coverage

  build:
    executor:
      name: node/default
      tag: 'lts'
    steps:
      - restore_cache:
          key: bjeco-INSTALLED-{{ .Revision }}
      - run:
          name: Build App
          command: yarn build
      - store_artifacts:
          path: ./build

workflows:
  quality:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - build:
          requires:
            - lint
            - test
