name: Dependabot PR

on: pull_request_target

jobs:
  dependabot-pr-review:
    permissions:
      pull-requests: write
      contents: write
    uses: brianespinosa/actions/.github/workflows/dependabot-pr-review.yml@main
    secrets: inherit

  dependabot-pr-nx-lint-fix:
    permissions:
      pull-requests: write
      contents: write
    uses: ./.github/workflows/local-lint.yml
    secrets: inherit
